version: "3.8"
services:
  rabbitmq3:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.12-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
        - '5672:5672'
        - '15672:15672'